### ISSUE TITLE
Can not append array with Parent Category key value. 

### ISSUE THREAD

**Issue by russell4** [russell4/LibreBudget#1]
```
Traceback (most recent call last):
  File "processorFunctions.py", line 78, in <module>
    main()
  File "processorFunctions.py", line 74, in main
    totalCategoryActualTransactionCSV()
  File "processorFunctions.py", line 50, in totalCategoryActualTransactionCSV
    parentCatArray.append(parentCat)
AttributeError: 'tuple' object has no attribute 'append'
```

**Comment by russell4** [comment]
Closed but separating the creation of the child category dictionary into another function.

**Comment by russell4** [comment]
Closed but separating the creation of the child category dictionary into another function.
